### ISSUE TITLE
Structuring

### ISSUE THREAD

**Issue by yikim01** [yikim01/battleship#1]
having an issue trying to figure out how to get my four variables of ships (shipA, shipB, shipC, shipD) to be var ships for my function so it is able to show in my consol as a hit miss or sunk

**Comment by ghost** [comment]
Hi Kim!

Please resubmit using the correct structure outlined in [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol).

If you want a consultation about how you are modeling your game, you can come directly to me. Good luck! Closed #1.
