### ISSUE TITLE
Clicking error when trying to implement event listener with a variable

### ISSUE THREAD

**Issue by yikim01** [yikim01/battleship#2]
# What user story am I working on?

 -When a user clicks on a specific cell to make their guess on where the battleship is they will get a message saying "hit" or "miss" based on the location of the ships.  I am having trouble connect the ships to the grid.
# What error am I getting?
- I am not getting an error in the console but no matter the code I put in, it just doesn't seems to want to recognize the location of the ships.
# What have I already attempted in trying to fix the error?

-To make sure it was not a syntax error I put it through jsbin. I also tried rewording a few times to make sure the computer understands what I am trying to do. I also moved my event listener from outside of my function to the inside of the function.

**Comment by ghost** [comment]
OK Kim,

Looking at your code, it's a mess. Bad indentation everywhere.

Adding more code has never solved a coding problem, ever!

I'm going to send you a PR with some changes. Come to me and we can talk about them.

**Comment by yikim01** [comment]
Working.
